server:
  port: 9090
  servlet:
    context-path: /app

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gestionlocationv2?serverTimezone=UTC
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
